version: "3.8"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
        #      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "8080:80/tcp"
    environment:
      - TZ=America/New_York
      - WEBPASSWORD=password
      - TEMPERATUREUNIT=f
      - DNS1=172.20.1.4#5054
      - DNS2=no
      - ServerIP=192.168.1.4
    dns:
      - 192.168.1.4      
      - 127.0.0.1
      # Volumes store your data between container upgrades
    volumes:
      - "/home/fabio/Docker/PiHole/etc-pihole:/etc/pihole"
      - "/home/fabio/Docker/PiHole/etc-dnsmasq.d:/etc/dnsmasq.d"    
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Recommended but not required (DHCP needs NET_ADMIN)      
    restart: unless-stopped
    networks:
       my_net:
         ipv4_address: 172.20.1.3

  cloudflared:
    image: visibilityspots/cloudflared
    container_name: cloudflared
    ports:
      - "5054:5054/tcp"
      - "5054:5054/udp"
    environment:
        TZ: America/New_York
        PORT: 5054
        ADDRESS: 0.0.0.0
        UPSTREAM1: https://208.67.222.222/dns-query
        UPSTREAM2: https://208.67.220.220/dns-query
    dns:
      - 192.168.1.4
      - 127.0.0.1    
    restart: unless-stopped
    networks:
       my_net:
         ipv4_address: 172.20.1.4            
    
networks:
    my_net:
     external:
       name: my_net

